name: The Jack Brunton Trust
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
google_maps_javascript_api_key: "AIzaSyD-l3HiyZMPxO9KSg4GfkvrDrrvJHdTLMs"
